TpInvestigacion.Web/Models/ErrorViewModel.cs
namespace TpInvestigacion.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TpInvestigacion.Web/Controllers/CadenaBloqueController.cs
using Microsoft.AspNetCore.Mvc;
using TpInvestigacion.Data.Entidades;
using TpInvestigacion.Servicio.Interfaces;

namespace TpInvestigacion.Web.Controllers
{
    public class CadenaBloqueController : Controller
    {
        readonly IServicio _servicio;

        public CadenaBloqueController(IServicio servicio)   // importantisimo tener este constructor para enlazar el constructor con el servicio
        {
            _servicio = servicio;
        }

        public IActionResult Agregar()
        {
            return View();
        }

        // Método para agregar un bloque a la cadena
        public IActionResult AgregarBloque(IFormCollection formulario)
        {

            _servicio.AgregarBloque(formulario["Datos"]);
            return Redirect("/CadenaBloque/Listar");
        }

        public IActionResult Listar()
        {
            List<Bloque> lista = _servicio.ListarBloques();
            if(lista == null)
            {
                return View("ListaVacia");
            }
            return View(lista);
        }

        public IActionResult Editar(int Id)
        {
            Bloque bloque = _servicio.BuscarBloquePorId(Id);
            return View(bloque);
        }

        [HttpPost]
        public IActionResult Editar(IFormCollection formulario)
        {
            Bloque bloqueEditado = new Bloque();
            bloqueEditado.Id = int.Parse(formulario["Id"]);
            bloqueEditado.Datos = formulario["Datos"];
            bloqueEditado.Hash = formulario["Hash"];
            bloqueEditado.HashAnterior = formulario["Hash_anterior"];
            bloqueEditado.Tiempo = DateTime.Parse(formulario["Tiempo"]);
            _servicio.ModificarBloque(bloqueEditado);
            return View();
        }

        [HttpGet]
        public IActionResult Eliminar(int Id)
        {
            _servicio.EliminarBloque(Id);
            return Redirect("/CadenaBloque/Listar");
        }

        public IActionResult DefinirIntegridad()
        {
            string resultado = _servicio.VerificarIntegridad();
            return View("DefinirIntegridad", resultado);
        }
    }
}

TpInvestigacion.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TpInvestigacion.Web.Models;

namespace TpInvestigacion.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TpInvestigacion.Web/Views/CadenaBloque/Agregar.cshtml
@model TpInvestigacion.Data.Entidades.Bloque

@{
    ViewData["Title"] = "Agregar";
}

<h1>Agregar</h1>

<h4>Bloque</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="CadenaBloque" asp-action="AgregarBloque">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Datos" class="control-label"></label>
                <input asp-for="Datos" class="form-control" />
                <span asp-validation-for="Datos" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

TpInvestigacion.Web/Views/CadenaBloque/DefinirIntegridad.cshtml
@model string
@{
    ViewData["Title"] = "DefinirIntegridad";
}

<h1>DefinirIntegridad</h1>
<h2>@Model</h2>

TpInvestigacion.Web/Views/CadenaBloque/ListaVacia.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>La lista de registro esta vacia</h3>

TpInvestigacion.Web/Views/CadenaBloque/Listar.cshtml
@model IEnumerable<TpInvestigacion.Data.Entidades.Bloque>

@{
    ViewData["Title"] = "Listar";
}

<h1>Listar</h1>

<p>
    <a asp-controller="CadenaBloque" asp-action="Agregar">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Datos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hash)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HashAnterior)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tiempo)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Datos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hash)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HashAnterior)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tiempo)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<br />
<p>
    <a asp-controller="CadenaBloque" asp-action="Agregar" class="btn btn-primary">Agregar</a>  
    <a asp-controller="CadenaBloque" asp-action="DefinirIntegridad" class="btn btn-primary">Analizar la integridad</a>
</p>

TpInvestigacion.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>
        Bienvenidos a nuestra página web que presenta un ejemplo básico de la
        aplicación de blockchain en la trazabilidad alimentaria. La trazabilidad
        alimentaria es esencial para garantizar la seguridad y calidad de los
        alimentos que consumimos. La tecnología blockchain se ha convertido en una
        herramienta importante para la trazabilidad de los alimentos, ya que permite
        un registro inmutable y seguro de toda la cadena de suministro,
        desde el origen hasta el punto de venta. En esta página, encontrarás un
        ejemplo simple pero efectivo de cómo se puede utilizar la tecnología blockchain
        para mejorar la trazabilidad alimentaria, proporcionando una mayor transparencia
        y confianza para los consumidores y las empresas en la industria alimentaria.
    </p>
    <br />
    <a asp-controller="CadenaBloque" asp-action="Listar" class="btn btn-primary">Listar registros</a>
    <a asp-controller="CadenaBloque" asp-action="Agregar" class="btn btn-primary">Agregar registro</a>
</div>

TpInvestigacion.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TpInvestigacion.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TpInvestigacion.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TpInvestigacion.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TpInvestigacion.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>